apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-hello-world
  template:
    metadata:
      labels:
        app: ruby-hello-world
    spec:
      containers:
        - name: ruby-hello-world
          image: vinothrlingam/shipit-infra:7
          imagePullPolicy: Always