apiVersion: v1
kind: Service
metadata:
  name: ruby-hello-world-service
spec:
  selector:
    app: ruby-hello-world
  type: NodePort
  ports:
    - name: http
      port: 4567
      nodePort: 30010